
	<!DOCTYPE scenarios [
		<!ELEMENT scenarios (scenario*)>
		<!ELEMENT scenario (description? | population-policy? |  dashboards? | charts-model-description? | population-result-filter? | zone-result-filter? | time-interval-result-filter? | error-result-filter? | rdv-fixed-vu-count-policy? | rdv-percentile-vu-count-policy? | rdv-manual-policy? | debug-policy? | request-path-exclusion-filter?)*>
		
	  	<!ELEMENT population-policy (duration-policy-entry?, volume-policy-entry?, start-stop-policy-entry?, runtime-policy?, lg-hosts)>
		<!ELEMENT volume-policy-entry (constant-volume-policy? | rampup-volume-policy? | peaks-volume-policy? | custom-volume-policy?)*>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT constant-volume-policy (#PCDATA)>
		<!ELEMENT rampup-volume-policy (#PCDATA)>
		<!ELEMENT peaks-volume-policy (#PCDATA)>
		<!ELEMENT custom-volume-policy (custom-load-node*)>
		<!ELEMENT custom-load-node (#PCDATA)>
		<!ELEMENT duration-policy-entry (#PCDATA)>
		<!ELEMENT start-stop-policy-entry (#PCDATA)>
		<!ELEMENT lg-hosts (lg-host-entry*)>
		<!ELEMENT lg-host-entry (#PCDATA)>
		<!ELEMENT runtime-policy (#PCDATA)>
		<!ELEMENT dashboards (#PCDATA)>
		<!ELEMENT charts-model-description (chart-description? | empty-chart-description?)*>
		<!ELEMENT empty-chart-description (#PCDATA)>
		<!ELEMENT chart-description (monitor-curve-description? | action-curve-description?)*>
		<!ELEMENT monitor-curve-description (#PCDATA)>
		<!ELEMENT action-curve-description (#PCDATA)>
		<!ELEMENT population-result-filter (#PCDATA)>
		<!ELEMENT error-result-filter (#PCDATA)>
		<!ELEMENT zone-result-filter (#PCDATA)>
		<!ELEMENT time-interval-result-filter (#PCDATA)>
		<!ELEMENT rdv-fixed-vu-count-policy (#PCDATA)>
		<!ELEMENT rdv-manual-policy (#PCDATA)>
		<!ELEMENT rdv-percentile-vu-count-policy (#PCDATA)>
		<!ELEMENT debug-policy (#PCDATA)>
		<!ELEMENT request-path-exclusion-filter (regexps?)>
		<!ELEMENT regexps (regexp*)>
		<!ELEMENT regexp (#PCDATA)>
		
		<!ATTLIST scenarios>

		<!ATTLIST scenario
		    uid CDATA #REQUIRED
		    prebenchVUName CDATA #IMPLIED
		    postbenchVUName CDATA #IMPLIED
		    postMonitoringTime CDATA #IMPLIED
		    preMonitoringTime CDATA #IMPLIED
		    virtualUsersStates CDATA #IMPLIED
		    slaProfileEnabled CDATA #IMPLIED
		    slaProfileUID CDATA #IMPLIED
		    slaProfileName CDATA #IMPLIED>
		    
		<!ATTLIST population-policy
			name CDATA #REQUIRED>
		    
		<!ATTLIST volume-policy-entry>
		    
		<!ATTLIST constant-volume-policy
			iterationNumber CDATA #IMPLIED
		    userNumber CDATA #REQUIRED>
		    
		<!ATTLIST rampup-volume-policy
			iterationNumber CDATA #IMPLIED
	   		initialUserNumber CDATA #REQUIRED
			maxUserNumber CDATA #REQUIRED
			delayTypeIncrement CDATA #REQUIRED
			delayIncrement CDATA #REQUIRED
			userIncrement CDATA #REQUIRED>
			
		<!ATTLIST peaks-volume-policy
			iterationNumber CDATA #IMPLIED
	   		defaultUserNumber CDATA #REQUIRED
			peakUserNumber CDATA #REQUIRED
			defaultDelayType CDATA #REQUIRED
			peakDelayType CDATA #REQUIRED
			defaultDelay CDATA #REQUIRED
			peakDelay CDATA #REQUIRED
			startPoint CDATA #REQUIRED>
			
		<!ATTLIST custom-volume-policy
			maxUsers CDATA #IMPLIED
			totalLength CDATA #IMPLIED
			useIteration CDATA #IMPLIED
			iteration CDATA #IMPLIED>
			
		<!ATTLIST custom-load-node
			users CDATA #REQUIRED
			time CDATA #REQUIRED
			iteration CDATA #REQUIRED
			position CDATA #REQUIRED>
			
		<!ATTLIST start-stop-policy-entry
			start-type CDATA #REQUIRED
			start-delay CDATA #IMPLIED
			start-population CDATA #IMPLIED
			stop-type CDATA #REQUIRED
			stop-delay CDATA #IMPLIED>
		
		<!ATTLIST duration-policy-entry
			type CDATA #IMPLIED
	   		time CDATA #IMPLIED
	   		timeUnit CDATA #IMPLIED
			iterations CDATA #IMPLIED>
					
		<!ATTLIST runtime-policy
	   		vuStartDelay CDATA #IMPLIED
	   		vuStartMode CDATA #IMPLIED
			continueOnError CDATA #IMPLIED
			thinktimePolicy CDATA #IMPLIED
			thinktimeValue CDATA #IMPLIED
			populationName CDATA #IMPLIED
			jsLogLevel CDATA #IMPLIED>
			
	   	<!ATTLIST dashboards
			defaultDashboardUid CDATA #REQUIRED>	
		<!ATTLIST charts-model-description
			name CDATA #IMPLIED>
		<!ATTLIST chart-description
			title CDATA #IMPLIED
			description CDATA #IMPLIED
			domainMarkerVisible CDATA #REQUIRED
			rangeMarkerVisible CDATA #REQUIRED
			chart-description-type CDATA #REQUIRED
			customID CDATA #IMPLIED
			typeName CDATA #IMPLIED
			includeInReport CDATA #IMPLIED
			xAxisMonitorName CDATA #IMPLIED
			xAxisConnectionName CDATA #IMPLIED
			xAxisMonitoredHostName CDATA #IMPLIED>
		<!ATTLIST empty-chart-description>
		<!ATTLIST monitor-curve-description
			benchUid CDATA #IMPLIED
			color CDATA #REQUIRED
			dashed CDATA #REQUIRED
			scale CDATA #IMPLIED
			selected CDATA #REQUIRED
			monitoredHostName CDATA #REQUIRED
			connectionName CDATA #REQUIRED
			monitorName CDATA #REQUIRED>
			
		<!ATTLIST action-curve-description
			benchUid CDATA #IMPLIED
			color CDATA #REQUIRED
			dashed CDATA #REQUIRED
			scale CDATA #IMPLIED
			selected CDATA #REQUIRED
			actionUid CDATA #IMPLIED
			statisticName CDATA #REQUIRED
			populationName CDATA #REQUIRED
			virtualUserUid CDATA #IMPLIED
			zoneName CDATA #REQUIRED>
			
        <!ATTLIST third-party-data-curve-description
            benchUid CDATA #IMPLIED
            color CDATA #REQUIRED
            dashed CDATA #REQUIRED
            scale CDATA #IMPLIED
            selected CDATA #REQUIRED
            hw CDATA #IMPLIED
            loc CDATA #IMPLIED
            path CDATA #REQUIRED
            script CDATA #IMPLIED
            soft CDATA #IMPLIED
            unit CDATA #REQUIRED>

		<!ATTLIST population-result-filter
			accepted-object-names CDATA #IMPLIED
			accepted-object-ids CDATA #REQUIRED>
		
		<!ATTLIST zone-result-filter
			accepted-object-names CDATA #IMPLIED
			accepted-object-ids CDATA #REQUIRED>
		
		<!ATTLIST time-interval-result-filter
			creationTimestampRelativeToBenchStartTime CDATA #REQUIRED
			endTimestampRelativeToBenchStartTime CDATA #REQUIRED>
		
		<!ATTLIST error-result-filter
			booleanValue CDATA #REQUIRED>

		<!ATTLIST rdv-fixed-vu-count-policy
			rendezVousName CDATA #REQUIRED
			timeout CDATA #REQUIRED
			isEnabled CDATA #REQUIRED
			fixedVirtualUserCount CDATA #REQUIRED>
			
		<!ATTLIST rdv-percentile-vu-count-policy
			rendezVousName CDATA #REQUIRED
			timeout CDATA #REQUIRED
			isEnabled CDATA #REQUIRED
			percentileVirtualUserCount CDATA #REQUIRED>
		
		<!ATTLIST rdv-manual-policy
			rendezVousName CDATA #REQUIRED
			timeout CDATA #REQUIRED
			isEnabled CDATA #REQUIRED>
			
		<!ATTLIST debug-policy
			mode CDATA #REQUIRED>
			
		<!ATTLIST request-path-exclusion-filter 
			isEnabled CDATA #REQUIRED>
	]>


<scenarios>
<scenario postMonitoringTime="-1" preMonitoringTime="-1" slaProfileEnabled="false" uid="scenario1" virtualUsersStates="true">
<!--****** POPULATION POLICY ******-->
<population-policy name="POPULATION3">
<duration-policy-entry iterations="1" time="600" timeUnit="0" type="2"/>
<volume-policy-entry>
<constant-volume-policy iterationNumber="1" userNumber="5"/>
</volume-policy-entry>
<start-stop-policy-entry start-delay="0" start-type="0" stop-delay="60000" stop-type="2"/>
<runtime-policy continueOnError="true" thinktimePolicy="0" thinktimeValue="5000" vuStartDelay="0" vuStartMode="0"/>
<!--****** POPULATION LG HOSTS ******-->
<lg-hosts>
<lg-host-entry>$zoneID=Default zone;$lgID=localhost:7100</lg-host-entry>
</lg-hosts>
</population-policy>
<dashboards defaultDashboardUid="Graph board"/>
<!--****** DASHBOARDS  ******-->
<charts-model-description name="Graph board">
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="User Load and Error Rate" typeName="CLASSIC">
<monitor-curve-description color="20,106,203" connectionName="NeoLoad" dashed="false" monitorName="UserLoad" monitoredHostName="NeoLoad" scale="1.0" selected="false"/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="200,0,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.errors" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="88,183,55" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.hit.rate" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="191,0,189" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.errors.per.s" zoneName=""/>
<action-curve-description actionUid="d78c18da-71b4-3805-92a4-d74fb7a5ab2e" color="42,89,26" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.hit.rate" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="153,153,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.average.duration" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="107,107,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.maximum.duration" zoneName=""/>
<action-curve-description actionUid="d78c18da-71b4-3805-92a4-d74fb7a5ab2e" color="20,210,210" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.average.duration" zoneName=""/>
<action-curve-description actionUid="d78c18da-71b4-3805-92a4-d74fb7a5ab2e" color="223,143,143" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.maximum.duration" zoneName=""/>
<action-curve-description actionUid="7ed8daca-007e-3d9e-b273-7a92d22bf638" color="236,153,22" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.average.duration" zoneName=""/>
<action-curve-description actionUid="7ed8daca-007e-3d9e-b273-7a92d22bf638" color="128,128,128" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.maximum.duration" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="244,239,0" dashed="false" populationName="" scale="100.0" selected="false" statisticName="result.throughput" zoneName=""/>
</chart-description>
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="Overall Throughput" typeName="CLASSIC">
<monitor-curve-description color="42,89,26" connectionName="NeoLoad" dashed="false" monitorName="throughput" monitoredHostName="NeoLoad" scale="1.0" selected="false"/>
</chart-description>
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="Load Generators CPU usage" typeName="CLASSIC">
<monitor-curve-description color="0,255,0" connectionName="NeoLoad" dashed="false" monitorName="lgcpu.localhost:7100" monitoredHostName="LG localhost:7100" scale="1.0" selected="false"/>
</chart-description>
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="Requests/s and Errors/s" typeName="CLASSIC">
<monitor-curve-description color="20,106,203" connectionName="NeoLoad" dashed="false" monitorName="UserLoad" monitoredHostName="NeoLoad" scale="1.0" selected="false"/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="88,183,55" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.hit.rate" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="200,0,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.errors.per.s" zoneName=""/>
</chart-description>
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="Page rate" typeName="CLASSIC">
<monitor-curve-description color="20,106,203" connectionName="NeoLoad" dashed="false" monitorName="UserLoad" monitoredHostName="NeoLoad" scale="1.0" selected="false"/>
<action-curve-description actionUid="d78c18da-71b4-3805-92a4-d74fb7a5ab2e" color="42,89,26" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.hit.rate" zoneName=""/>
</chart-description>
<chart-description autoRange="true" chart-description-type="chart-description-type" domainMarkerVisible="true" granularityLevel="0" historyState="XMIN" includeInReport="false" rangeMarkerVisible="true" title="Response times (req.)" typeName="CLASSIC">
<monitor-curve-description color="20,106,203" connectionName="NeoLoad" dashed="false" monitorName="UserLoad" monitoredHostName="NeoLoad" scale="1.0" selected="false"/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="153,153,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.average.duration" zoneName=""/>
<action-curve-description actionUid="2ee035d5-0178-378f-8d0a-63218f082d2f" color="107,107,0" dashed="false" populationName="" scale="1.0" selected="false" statisticName="result.maximum.duration" zoneName=""/>
</chart-description>
</charts-model-description>
<!--****** END DASHBOARDS  ******-->
<!--****** START DATA AUTO FILTERS  ******-->
<auto-filters>
<time-interval-result-filter creationTimestampRelativeToBenchStartTime="0" endTimestampRelativeToBenchStartTime="1800000"/>
</auto-filters>
<!--****** END DATA AUTO FILTERS  ******-->
<!--****** START DATA FILTERS  ******-->
<!--****** END DATA FILTERS  ******-->
<!--****** START RENDEZ-VOUS POLICIES  ******-->
<!--****** END RENDEZ-VOUS POLICIES  ******-->
<!--****** START DEBUG POLICY ******-->
<debug-policy mode="1"/>
<!--****** END DEBUG POLICY ******-->
<!--****** START VU STATES ******-->
<!--****** END VU STATES ******-->
<request-path-exclusion-filter isEnabled="false">
<regexps>
<regexp>.*\.jpg</regexp>
<regexp>.*\.jpeg</regexp>
<regexp>.*\.gif</regexp>
<regexp>.*\.png</regexp>
<regexp>.*\.bmp</regexp>
<regexp>.*\.css</regexp>
<regexp>.*\.js</regexp>
<regexp>.*\.swf</regexp>
<regexp>.*\.ico</regexp>
<regexp>.*\.jar</regexp>
<regexp>.*\.class</regexp>
<regexp>.*\.properties</regexp>
</regexps>
</request-path-exclusion-filter>
</scenario>
</scenarios>
